# Generated by Django 3.2.6 on 2021-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
