# Generated by Django 3.2.6 on 2021-08-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20210826_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='check_in_date',
            field=models.DateField(),
        ),
    ]
