# Generated by Django 3.2.6 on 2021-08-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20210824_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='comments',
            field=models.ManyToManyField(null=True, to='films.FilmComment'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rate',
            field=models.ManyToManyField(null=True, to='films.FilmRate'),
        ),
    ]
